### ISSUE TITLE
[調査]音楽コントロール何を使って実装すればいいのか問題

### ISSUE THREAD

**Issue by ibukinson** [ibukinson/operate_music#1]
そこらへんに転がってるかと思ったけど、意外とない
# 調査結果
flutterは無理そう
実装はAndroid,iOSはそれぞれで実装する
## 参考になりそうなサイト
[iOSAudioPlayer](https://cocoapods.org/pods/iOSAudioPlayer)
[Swift4で音楽プレーヤーを作ってみた！](https://qiita.com/yanashi222/items/97b12b16174030f4d3cb)

**Comment by ibukinson** [comment]
やばい
flutterで出来ないかも

**Comment by ibukinson** [comment]
https://pub.dev/documentation/audio_service/latest/
これで出来なかったら絶望

**Comment by ibuki-iida** [comment]
ネイティブで実装する方が早いかも

**Comment by ibukinson** [comment]
ネイティブでやる！！

**Comment by ibukinson** [comment]
参考になりそうなサイト
[iOSAudioPlayer](https://cocoapods.org/pods/iOSAudioPlayer)
[Swift4で音楽プレーヤーを作ってみた！](https://qiita.com/yanashi222/items/97b12b16174030f4d3cb)

**Comment by ibukinson** [comment]
実装に移る為close
